export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const ADD_USER = 'ADD_USER';
export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_COUNT = 'SET_COUNT';
export const DECEREASE_COUNT = 'DECEREASE_COUNT';
export const SET_LIST = 'SET_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
